### ISSUE TITLE
Replace Year filter

### ISSUE THREAD

**Issue by MikeRosTX** [finspin/gotodevops.org#116]
Recommend replacing the Year filter for something like a **_Date Range start:_** and **_Date Range end:_** drop-down boxes or some other solution. Because currently there's no way to search like future dates to plan travel arrangements ahead of time.

**Comment by finspin** [comment]
Sliding month filter sounds like a good idea. 👍 

How did you mean there is no way to search for future dates? You can still click the future months to see the upcoming conferences.

**Comment by MikeRosTX** [comment]
So as an example, if I want to do a filter search for conferences happening in either April or May of 2020 there no way to do it.
![image](https://user-images.githubusercontent.com/11631454/64986567-e32e6380-d88c-11e9-93c1-b0fde37f30a4.png)

**Comment by finspin** [comment]
Ah right, now I fully understand. As we approach 2020 and have more conferences to display (currently only 1) there will be another row of month filters with header Year 2020. That's how I've done it for 2018 / 2019.

Having a slider is another option.
