### ISSUE TITLE
Issue opening event from frame

### ISSUE THREAD

**Issue by MikeRosTX** [finspin/gotodevops.org#119]
Not sure if this is a bug or expected results. Opening this site within a frame produced unexpected results. But directly from GoToDevOps.org works as expected.

![2019-09-16_13-37-01](https://user-images.githubusercontent.com/11631454/64984162-ce9b9c80-d887-11e9-8ddf-f364f1b7fbfd.png)

![2019-09-16_13-36-06](https://user-images.githubusercontent.com/11631454/64984176-d3f8e700-d887-11e9-914d-115a33943fb9.png)

**Comment by MikeRosTX** [comment]
Could it have something to do with destination site wanting to collect cookie details?

**Comment by finspin** [comment]
That website explicitly blocks external iframes, that's why the link won't open.

**Comment by MikeRosTX** [comment]
OK this issue can be closed as **_By Design_**.
