### ISSUE TITLE
Multi-location events

### ISSUE THREAD

**Issue by obfuscurity** [finspin/gotodevops.org#123]
Hi @finspin, curious for how you recommend distinguishing multiple events in `conferences.json`. For example, this year we had "Monitorama PDX 2019" and "Monitorama Baltimore 2019", in Portland and Baltimore, respectively. There is currently one entry for "Monitorama" (PDX event); if we schedule another event for 2020, how would you recommend we organize them?

**Comment by finspin** [comment]
Hi @obfuscurity, PDX and Baltimore can be 2 separate entries in `conferences.json` since they are 2 separate events. For the 2020 events, just create yet another entry. The site will display only future events so you don't need to care about the old entries.

**Comment by obfuscurity** [comment]
Sounds good, thanks.
