### ISSUE TITLE
JavaScript errors on load, filtering doesn't work

### ISSUE THREAD

**Issue by mgrecar** [finspin/gotodevops.org#78]
Just loading the page and doing nothing dumps this in the console: 
```
e7cdd4635d83e526a4b6.js:1 [nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```
Followed by the rest of the mangled JS stack trace.  Consequently, filtering doesn't seem to work at all. 

Running:
Chrome - Version 71.0.3578.98 (Official Build) (64-bit)
macOS Mojave 10.14.2

**Comment by 0sanity** [comment]
I have the same error on
Windows 10 x64 1809
Chrome 71.0.3578.98
Firefox 64.0.2 x64
Edge 44.17763.1.0

**Comment by finspin** [comment]
I disabled the filtering button on mobile which I suspect is the problematic component.

@mgrecar , @0sanity would you mind trying again? Does the filtering work now?

**Comment by mgrecar** [comment]
Fixed it from my perspective, yep 👍
